export {default as About} from './about/About'
export {default as Contact} from './contact/Contact'
export {default as Features} from './features/Features'
export {default as Hero} from './hero/Hero'
export {default as Pricing} from './pricing/Pricing'
export {default as Projects} from './projects/Projects'
export {default as Beats} from './projects/Projects'
export {default as Users} from './users/Users'